import { afterEach, describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { generateSuite } from "../scripts/generate-suite.ts";

const TEMPORARY_ROOTS: string[] = [];

async function writeJson(path: string, value: unknown): Promise<void> {
	await writeFile(path, `${JSON.stringify(value, null, "\t")}\n`);
}

async function createRepository(): Promise<string> {
	const root = await mkdtemp(join(tmpdir(), "pi-stuff-generator-"));
	TEMPORARY_ROOTS.push(root);

	await mkdir(join(root, "packages", "pi-stuff"), { recursive: true });
	await writeJson(join(root, "packages", "pi-stuff", "package.json"), {
		name: "@jczhang02/pi-stuff",
		version: "0.0.0",
		dependencies: { zod: "4.4.3" },
		bundledDependencies: ["zod"],
	});
	await writeJson(join(root, "packages", "pi-stuff", "suite.json"), {
		schemaVersion: 1,
		capabilities: ["@jczhang02/pi-beta", "@jczhang02/pi-stuff-agents", "@jczhang02/pi-alpha"],
	});

	for (const [directory, name, version] of [
		["pi-alpha", "@jczhang02/pi-alpha", "0.1.2"],
		["pi-beta", "@jczhang02/pi-beta", "0.3.4"],
		["pi-stuff-agents", "@jczhang02/pi-stuff-agents", "0.5.6"],
	] as const) {
		await mkdir(join(root, "packages", directory), { recursive: true });
		await writeJson(join(root, "packages", directory, "package.json"), { name, version });
	}

	return root;
}

afterEach(async () => {
	await Promise.all(TEMPORARY_ROOTS.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe("generateSuite", () => {
	test("writes an ordered fail-fast aggregate and exact bundled dependencies", async () => {
		const root = await createRepository();

		const result = await generateSuite(root, "write");

		expect(result.changedFiles).toEqual(["packages/pi-stuff/index.ts", "packages/pi-stuff/package.json"]);
		expect(
			await readFile(join(root, "packages", "pi-stuff", "index.ts"), "utf8"),
		).toBe(`// Generated by scripts/generate-suite.ts. Do not edit directly.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import piAlpha from "@jczhang02/pi-alpha";
import piBeta from "@jczhang02/pi-beta";
import piStuffAgents from "@jczhang02/pi-stuff-agents";

type CapabilityFactory = (pi: ExtensionAPI) => void | Promise<void>;

const CAPABILITIES: readonly CapabilityFactory[] = [piBeta, piStuffAgents, piAlpha];

export default async function piStuff(pi: ExtensionAPI): Promise<void> {
\tfor (const capability of CAPABILITIES) {
\t\tawait capability(pi);
\t}
}
`);
		expect(JSON.parse(await readFile(join(root, "packages", "pi-stuff", "package.json"), "utf8"))).toEqual({
			name: "@jczhang02/pi-stuff",
			version: "0.0.0",
			dependencies: {
				zod: "4.4.3",
				"@jczhang02/pi-beta": "0.3.4",
				"@jczhang02/pi-stuff-agents": "0.5.6",
				"@jczhang02/pi-alpha": "0.1.2",
			},
			bundledDependencies: ["@jczhang02/pi-beta", "@jczhang02/pi-stuff-agents", "@jczhang02/pi-alpha", "zod"],
		});
	});

	test("reports generated drift without rewriting the working tree", async () => {
		const root = await createRepository();
		const indexPath = join(root, "packages", "pi-stuff", "index.ts");
		await generateSuite(root, "write");
		await writeFile(indexPath, "stale\n");

		await expect(generateSuite(root, "check")).rejects.toThrow(
			"Generated Suite files are stale: packages/pi-stuff/index.ts",
		);
		expect(await readFile(indexPath, "utf8")).toBe("stale\n");
	});
});
