// Generated by scripts/generate-suite.ts. Do not edit directly.

import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import piStuffAgents from "@jczhang02/pi-stuff-agents";
import piStuffBtw from "@jczhang02/pi-stuff-btw";
import piStuffCodex from "@jczhang02/pi-stuff-codex";
import piStuffContext from "@jczhang02/pi-stuff-context";
import piStuffGoal from "@jczhang02/pi-stuff-goal";
import piStuffMcp from "@jczhang02/pi-stuff-mcp";
import piStuffRtk from "@jczhang02/pi-stuff-rtk";
import piStuffTodo from "@jczhang02/pi-stuff-todo";
import piStuffTools from "@jczhang02/pi-stuff-tools";
import piStuffUi from "@jczhang02/pi-stuff-ui";
import piStuffWeb from "@jczhang02/pi-stuff-web";
import piStuffWork from "@jczhang02/pi-stuff-work";

type CapabilityFactory = (pi: ExtensionAPI) => void | Promise<void>;

const CAPABILITIES: readonly CapabilityFactory[] = [
	piStuffUi,
	piStuffTools,
	piStuffRtk,
	piStuffCodex,
	piStuffGoal,
	piStuffContext,
	piStuffWeb,
	piStuffMcp,
	piStuffWork,
	piStuffAgents,
	piStuffTodo,
	piStuffBtw,
];

export default async function piStuff(pi: ExtensionAPI): Promise<void> {
	process.env["PI_STUFF_CHILD_BASE_EXTENSION_PATH"] = fileURLToPath(import.meta.url);
	for (const capability of CAPABILITIES) {
		await capability(pi);
	}
}
