import { readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const GENERATED_HEADER = "// Generated by scripts/generate-suite.ts. Do not edit directly.";

const CAPABILITY_MODULES = {
	"conversation-ui": "conversationUi",
	"tool-display": "toolDisplay",
	rtk: "rtk",
	codex: "codex",
	goal: "goal",
	"context-management": "contextManagement",
	web: "web",
	mcp: "mcp",
	"background-work": "backgroundWork",
	subagents: "subagents",
	todo: "todo",
	btw: "btw",
} as const;

export type CapabilityModule = keyof typeof CAPABILITY_MODULES;
export type GenerationMode = "check" | "write";

export interface GenerationResult {
	changedFiles: string[];
}

interface SuiteRegistry {
	schemaVersion?: unknown;
	capabilities?: unknown;
	tools?: unknown;
	deferredTools?: unknown;
	optionalTools?: unknown;
}

async function readJson<T>(path: string): Promise<T> {
	return JSON.parse(await readFile(path, "utf8")) as T;
}

function renderToolNamesConstant(identifier: string, names: readonly string[]): string {
	const inline = `const ${identifier} = [${names.map((name) => JSON.stringify(name)).join(", ")}] as const;`;
	return inline.length <= 120
		? inline
		: `const ${identifier} = [\n${names.map((name) => `\t${JSON.stringify(name)},`).join("\n")}\n] as const;`;
}

function renderCapabilityImport(capability: CapabilityModule): string {
	const identifier = CAPABILITY_MODULES[capability];
	const specifier = `./src/${capability}/index.js`;
	if (capability === "tool-display") {
		return `import ${identifier}, {\n\tassertSuiteToolActivityCoverage,\n\tcreateSuiteToolRegistrationTracker,\n} from "${specifier}";`;
	}
	return `import ${identifier} from "${specifier}";`;
}

function renderIndex(
	capabilities: readonly CapabilityModule[],
	toolNames: readonly string[],
	optionalToolNames: readonly string[],
	deferredToolNames: readonly string[],
): string {
	const hasSubagents = capabilities.includes("subagents");
	if ((toolNames.length > 0 || deferredToolNames.length > 0) && !capabilities.includes("tool-display")) {
		throw new Error("A Suite Tool inventory requires the tool-display module");
	}

	// Import order is presentation-only. Keep it deterministic for Biome while the
	// CAPABILITIES array below preserves the installation order from suite.json.
	const imports = [...capabilities].sort().map(renderCapabilityImport);
	const identifiers = capabilities.map((capability) =>
		capability === "subagents" ? "registerSuiteSubagents" : CAPABILITY_MODULES[capability],
	);
	const importBlock = [
		...(hasSubagents ? ['import { fileURLToPath } from "node:url";'] : []),
		'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";',
		...imports,
	].join("\n");
	const capabilityPrefix = "const CAPABILITIES: readonly CapabilityFactory[] = ";
	const inlineCapabilities = `[${identifiers.join(", ")}]`;
	const capabilityDeclaration =
		capabilityPrefix.length + inlineCapabilities.length + 1 <= 120
			? `${capabilityPrefix}${inlineCapabilities};`
			: `${capabilityPrefix}[\n${identifiers.map((identifier) => `\t${identifier},`).join("\n")}\n];`;
	const coverageArguments = [
		"pi",
		"SUITE_TOOL_NAMES",
		"registrations.toolNames",
		...(optionalToolNames.length > 0 || deferredToolNames.length > 0
			? [optionalToolNames.length > 0 ? "OPTIONAL_SUITE_TOOL_NAMES" : "[]"]
			: []),
		...(deferredToolNames.length > 0 ? ["DEFERRED_SUITE_TOOL_NAMES"] : []),
	];
	const coverageCall = `assertSuiteToolActivityCoverage(\n${coverageArguments
		.map((argument) => `\t\t\t${argument},`)
		.join("\n")}\n\t\t)`;
	const sections = [
		GENERATED_HEADER,
		importBlock,
		"type CapabilityFactory = (pi: ExtensionAPI) => void | Promise<void>;",
		...(hasSubagents
			? [
					`const CHILD_BASE_EXTENSION_PATH = fileURLToPath(import.meta.url);

function registerSuiteSubagents(pi: ExtensionAPI): void | Promise<void> {
	return subagents(pi, { childBaseExtensionPath: CHILD_BASE_EXTENSION_PATH });
}`,
				]
			: []),
		capabilityDeclaration,
		...(toolNames.length > 0
			? [
					renderToolNamesConstant("SUITE_TOOL_NAMES", toolNames),
					...(deferredToolNames.length > 0
						? [renderToolNamesConstant("DEFERRED_SUITE_TOOL_NAMES", deferredToolNames)]
						: []),
					...(optionalToolNames.length > 0
						? [renderToolNamesConstant("OPTIONAL_SUITE_TOOL_NAMES", optionalToolNames)]
						: []),
				]
			: []),
		`export default async function piStuff(pi: ExtensionAPI): Promise<void> {
${toolNames.length > 0 ? "\tconst registrations = createSuiteToolRegistrationTracker(pi);\n" : ""}\tfor (const capability of CAPABILITIES) {
\t\tawait capability(${toolNames.length > 0 ? "registrations.api" : "pi"});
\t}${toolNames.length > 0 ? `\n\tpi.on("session_start", () =>\n\t\t${coverageCall},\n\t);` : ""}
}`,
	];
	return `${sections.join("\n\n")}\n`;
}

function parseCapabilities(registry: SuiteRegistry): CapabilityModule[] {
	if (registry.schemaVersion !== 2) {
		throw new Error("packages/pi-stuff/suite.json must use schemaVersion 2");
	}
	if (!Array.isArray(registry.capabilities) || !registry.capabilities.every((value) => typeof value === "string")) {
		throw new Error("packages/pi-stuff/suite.json capabilities must be an array of internal module IDs");
	}
	const capabilities = registry.capabilities as string[];
	if (new Set(capabilities).size !== capabilities.length) {
		throw new Error("packages/pi-stuff/suite.json contains duplicate capabilities");
	}
	for (const capability of capabilities) {
		if (!Object.hasOwn(CAPABILITY_MODULES, capability)) {
			throw new Error(`Unknown Capability Module: ${capability}`);
		}
	}
	return capabilities as CapabilityModule[];
}

function parseTools(registry: SuiteRegistry, field: "tools" | "optionalTools" | "deferredTools"): string[] {
	const value = registry[field];
	if (value === undefined && field !== "tools") return [];
	if (!Array.isArray(value) || !value.every((entry) => typeof entry === "string" && entry.length > 0)) {
		throw new Error(`packages/pi-stuff/suite.json ${field} must be an array of Tool names`);
	}
	if (new Set(value).size !== value.length) {
		throw new Error(`packages/pi-stuff/suite.json contains duplicate ${field}`);
	}
	return value as string[];
}

function assertDisjointTools(
	required: readonly string[],
	optional: readonly string[],
	deferred: readonly string[],
): void {
	const seen = new Set(required);
	for (const name of [...optional, ...deferred]) {
		if (seen.has(name)) throw new Error(`Suite Tool inventories overlap at ${name}`);
		seen.add(name);
	}
}

async function applyGeneratedFile(path: string, content: string, mode: GenerationMode): Promise<boolean> {
	const current = await readFile(path, "utf8").catch(() => undefined);
	if (current === content) return false;
	if (mode === "write") await writeFile(path, content);
	return true;
}

export async function generateSuite(rootDirectory: string, mode: GenerationMode): Promise<GenerationResult> {
	const root = resolve(rootDirectory);
	const packageDirectory = join(root, "packages", "pi-stuff");
	const indexPath = join(packageDirectory, "index.ts");
	const registry = await readJson<SuiteRegistry>(join(packageDirectory, "suite.json"));
	const capabilities = parseCapabilities(registry);
	const requiredTools = parseTools(registry, "tools");
	const optionalTools = parseTools(registry, "optionalTools");
	const deferredTools = parseTools(registry, "deferredTools");
	assertDisjointTools(requiredTools, optionalTools, deferredTools);
	const generatedIndex = renderIndex(capabilities, requiredTools, optionalTools, deferredTools);
	const changedFiles = (await applyGeneratedFile(indexPath, generatedIndex, mode)) ? [relative(root, indexPath)] : [];
	if (mode === "check" && changedFiles.length > 0) {
		throw new Error(`Generated Suite files are stale: ${changedFiles.join(", ")}`);
	}
	return { changedFiles };
}

if (import.meta.main) {
	const arguments_ = process.argv.slice(2);
	if (arguments_.some((argument) => argument !== "--check")) {
		throw new Error(`Unknown arguments: ${arguments_.join(" ")}`);
	}
	const mode: GenerationMode = arguments_.includes("--check") ? "check" : "write";
	const result = await generateSuite(resolve(import.meta.dir, ".."), mode);
	if (mode === "write") {
		console.log(
			result.changedFiles.length > 0 ? `Generated ${result.changedFiles.join(", ")}` : "Suite files are current",
		);
	}
}
