import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const AGGREGATE_DIRECTORY = "pi-stuff";
const GENERATED_HEADER = "// Generated by scripts/generate-suite.ts. Do not edit directly.";
const PACKAGE_PREFIX = "@jczhang02/pi-";

export type GenerationMode = "check" | "write";

export interface GenerationResult {
	changedFiles: string[];
}

interface PackageManifest {
	name?: unknown;
	version?: unknown;
	dependencies?: unknown;
	bundledDependencies?: unknown;
	[key: string]: unknown;
}

interface SuiteRegistry {
	schemaVersion?: unknown;
	capabilities?: unknown;
	tools?: unknown;
	deferredTools?: unknown;
	optionalTools?: unknown;
}

async function readJson<T>(path: string): Promise<T> {
	return JSON.parse(await readFile(path, "utf8")) as T;
}

function capabilityIdentifier(packageName: string): string {
	const unscopedName = packageName.slice("@jczhang02/".length);
	return unscopedName.replace(/-([a-z0-9])/g, (_, character: string) => character.toUpperCase());
}

function renderToolNamesConstant(identifier: string, names: readonly string[]): string {
	const inline = `const ${identifier} = [${names.map((name) => JSON.stringify(name)).join(", ")}] as const;`;
	return inline.length <= 120
		? inline
		: `const ${identifier} = [\n${names.map((name) => `\t${JSON.stringify(name)},`).join("\n")}\n] as const;`;
}

function renderIndex(
	capabilities: readonly string[],
	toolNames: readonly string[],
	optionalToolNames: readonly string[],
	deferredToolNames: readonly string[],
): string {
	if ((toolNames.length > 0 || deferredToolNames.length > 0) && !capabilities.includes("@jczhang02/pi-stuff-tools")) {
		throw new Error("An Aggregate Tool inventory requires @jczhang02/pi-stuff-tools");
	}
	const imports = [...capabilities]
		.sort((left, right) => left.localeCompare(right))
		.map((packageName) =>
			packageName === "@jczhang02/pi-stuff-tools"
				? `import ${capabilityIdentifier(packageName)}, {\n\tassertSuiteToolActivityCoverage,\n\tcreateSuiteToolRegistrationTracker,\n} from "${packageName}";`
				: `import ${capabilityIdentifier(packageName)} from "${packageName}";`,
		);
	const identifiers = capabilities.map(capabilityIdentifier);
	const importBlock = [`import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";`, ...imports].join("\n");
	const capabilityPrefix = "const CAPABILITIES: readonly CapabilityFactory[] = ";
	const inlineCapabilities = `[${identifiers.join(", ")}]`;
	const capabilityDeclaration =
		capabilityPrefix.length + inlineCapabilities.length + 1 <= 120
			? `${capabilityPrefix}${inlineCapabilities};`
			: `${capabilityPrefix}[\n${identifiers.map((identifier) => `\t${identifier},`).join("\n")}\n];`;
	const coverageArguments = [
		"pi",
		"AGGREGATE_TOOL_NAMES",
		"registrations.toolNames",
		...(optionalToolNames.length > 0 || deferredToolNames.length > 0
			? [optionalToolNames.length > 0 ? "OPTIONAL_AGGREGATE_TOOL_NAMES" : "[]"]
			: []),
		...(deferredToolNames.length > 0 ? ["DEFERRED_AGGREGATE_TOOL_NAMES"] : []),
	];
	const coverageCall = `assertSuiteToolActivityCoverage(\n${coverageArguments.map((argument) => `\t\t\t${argument},`).join("\n")}\n\t\t)`;
	const sections = [
		GENERATED_HEADER,
		importBlock,
		"type CapabilityFactory = (pi: ExtensionAPI) => void | Promise<void>;",
		capabilityDeclaration,
		...(toolNames.length > 0
			? [
					renderToolNamesConstant("AGGREGATE_TOOL_NAMES", toolNames),
					...(deferredToolNames.length > 0
						? [renderToolNamesConstant("DEFERRED_AGGREGATE_TOOL_NAMES", deferredToolNames)]
						: []),
					...(optionalToolNames.length > 0
						? [renderToolNamesConstant("OPTIONAL_AGGREGATE_TOOL_NAMES", optionalToolNames)]
						: []),
				]
			: []),
		`export default async function piStuff(pi: ExtensionAPI): Promise<void> {
${toolNames.length > 0 ? "\tconst registrations = createSuiteToolRegistrationTracker(pi);\n" : ""}\tfor (const capability of CAPABILITIES) {
\t\tawait capability(${toolNames.length > 0 ? "registrations.api" : "pi"});
\t}${toolNames.length > 0 ? `\n\tpi.on("session_start", () =>\n\t\t${coverageCall},\n\t);` : ""}
}`,
	];
	return `${sections.join("\n\n")}\n`;
}

function parseRegistry(registry: SuiteRegistry): string[] {
	if (registry.schemaVersion !== 1) {
		throw new Error("packages/pi-stuff/suite.json must use schemaVersion 1");
	}
	if (!Array.isArray(registry.capabilities) || !registry.capabilities.every((value) => typeof value === "string")) {
		throw new Error("packages/pi-stuff/suite.json capabilities must be an array of package names");
	}
	const capabilities = registry.capabilities as string[];
	if (new Set(capabilities).size !== capabilities.length) {
		throw new Error("packages/pi-stuff/suite.json contains duplicate capabilities");
	}
	for (const packageName of capabilities) {
		if (!packageName.startsWith(PACKAGE_PREFIX) || packageName === "@jczhang02/pi-stuff") {
			throw new Error(`Invalid Capability Package name: ${packageName}`);
		}
	}
	return capabilities;
}

function parseTools(registry: SuiteRegistry): string[] {
	if (
		!Array.isArray(registry.tools) ||
		!registry.tools.every((value) => typeof value === "string" && value.length > 0)
	) {
		throw new Error("packages/pi-stuff/suite.json tools must be an array of Tool names");
	}
	const tools = registry.tools as string[];
	if (new Set(tools).size !== tools.length) throw new Error("packages/pi-stuff/suite.json contains duplicate Tools");
	return tools;
}

function parseOptionalTools(registry: SuiteRegistry, requiredTools: readonly string[]): string[] {
	if (registry.optionalTools === undefined) return [];
	if (
		!Array.isArray(registry.optionalTools) ||
		!registry.optionalTools.every((value) => typeof value === "string" && value.length > 0)
	) {
		throw new Error("packages/pi-stuff/suite.json optionalTools must be an array of Tool names");
	}
	const tools = registry.optionalTools as string[];
	if (new Set(tools).size !== tools.length) {
		throw new Error("packages/pi-stuff/suite.json contains duplicate optional Tools");
	}
	const overlap = tools.filter((name) => requiredTools.includes(name));
	if (overlap.length > 0) {
		throw new Error(`Aggregate Tools cannot be both required and optional: ${overlap.join(", ")}`);
	}
	return tools;
}

function parseDeferredTools(
	registry: SuiteRegistry,
	requiredTools: readonly string[],
	optionalTools: readonly string[],
): string[] {
	if (registry.deferredTools === undefined) return [];
	if (
		!Array.isArray(registry.deferredTools) ||
		!registry.deferredTools.every((value) => typeof value === "string" && value.length > 0)
	) {
		throw new Error("packages/pi-stuff/suite.json deferredTools must be an array of Tool names");
	}
	const tools = registry.deferredTools as string[];
	if (new Set(tools).size !== tools.length) {
		throw new Error("packages/pi-stuff/suite.json contains duplicate deferred Tools");
	}
	const overlap = tools.filter((name) => requiredTools.includes(name) || optionalTools.includes(name));
	if (overlap.length > 0) {
		throw new Error(
			`Aggregate Tools cannot be required, deferred, or optional at the same time: ${overlap.join(", ")}`,
		);
	}
	return tools;
}

async function readWorkspacePackages(packagesDirectory: string): Promise<Map<string, PackageManifest>> {
	const packages = new Map<string, PackageManifest>();
	for (const entry of await readdir(packagesDirectory, {
		withFileTypes: true,
	})) {
		if (!entry.isDirectory() || entry.name === AGGREGATE_DIRECTORY) {
			continue;
		}
		const manifest = await readJson<PackageManifest>(join(packagesDirectory, entry.name, "package.json"));
		if (typeof manifest.name !== "string") {
			throw new Error(`packages/${entry.name}/package.json must declare a package name`);
		}
		packages.set(manifest.name, manifest);
	}
	return packages;
}

function updateManifest(
	manifest: PackageManifest,
	capabilities: readonly string[],
	workspacePackages: ReadonlyMap<string, PackageManifest>,
): PackageManifest {
	const existingDependencies =
		typeof manifest.dependencies === "object" && manifest.dependencies !== null
			? (manifest.dependencies as Record<string, unknown>)
			: {};
	const dependencies: Record<string, unknown> = {};
	const externalBundledDependencies = Array.isArray(manifest.bundledDependencies)
		? manifest.bundledDependencies.filter(
				(dependency): dependency is string =>
					typeof dependency === "string" &&
					!dependency.startsWith(PACKAGE_PREFIX) &&
					Object.hasOwn(existingDependencies, dependency),
			)
		: [];
	for (const [packageName, version] of Object.entries(existingDependencies)) {
		if (!packageName.startsWith(PACKAGE_PREFIX)) {
			dependencies[packageName] = version;
		}
	}
	for (const packageName of capabilities) {
		const capabilityManifest = workspacePackages.get(packageName);
		if (!capabilityManifest) {
			throw new Error(`Capability Package is not a workspace: ${packageName}`);
		}
		if (typeof capabilityManifest.version !== "string") {
			throw new Error(`${packageName} must declare a version`);
		}
		dependencies[packageName] = capabilityManifest.version;
	}
	return {
		...manifest,
		dependencies,
		bundledDependencies: [...capabilities, ...externalBundledDependencies],
	};
}

async function applyGeneratedFile(path: string, content: string, mode: GenerationMode): Promise<boolean> {
	const current = await readFile(path, "utf8").catch(() => undefined);
	if (current === content) {
		return false;
	}
	if (mode === "write") {
		await writeFile(path, content);
	}
	return true;
}

export async function generateSuite(rootDirectory: string, mode: GenerationMode): Promise<GenerationResult> {
	const root = resolve(rootDirectory);
	const packagesDirectory = join(root, "packages");
	const aggregateDirectory = join(packagesDirectory, AGGREGATE_DIRECTORY);
	const manifestPath = join(aggregateDirectory, "package.json");
	const indexPath = join(aggregateDirectory, "index.ts");
	const registry = await readJson<SuiteRegistry>(join(aggregateDirectory, "suite.json"));
	const capabilities = parseRegistry(registry);
	const toolNames = parseTools(registry);
	const optionalToolNames = parseOptionalTools(registry, toolNames);
	const deferredToolNames = parseDeferredTools(registry, toolNames, optionalToolNames);
	const workspacePackages = await readWorkspacePackages(packagesDirectory);
	const manifest = await readJson<PackageManifest>(manifestPath);
	const generatedManifest = `${JSON.stringify(updateManifest(manifest, capabilities, workspacePackages), null, "\t")}\n`;
	const generatedIndex = renderIndex(capabilities, toolNames, optionalToolNames, deferredToolNames);
	const changedFiles: string[] = [];

	for (const [path, content] of [
		[indexPath, generatedIndex],
		[manifestPath, generatedManifest],
	] as const) {
		if (await applyGeneratedFile(path, content, mode)) {
			changedFiles.push(relative(root, path));
		}
	}

	if (mode === "check" && changedFiles.length > 0) {
		throw new Error(`Generated Suite files are stale: ${changedFiles.join(", ")}`);
	}
	return { changedFiles };
}

if (import.meta.main) {
	const arguments_ = process.argv.slice(2);
	if (arguments_.some((argument) => argument !== "--check")) {
		throw new Error(`Unknown arguments: ${arguments_.join(" ")}`);
	}
	const mode: GenerationMode = arguments_.includes("--check") ? "check" : "write";
	const result = await generateSuite(resolve(import.meta.dir, ".."), mode);
	if (mode === "write") {
		console.log(
			result.changedFiles.length > 0 ? `Generated ${result.changedFiles.join(", ")}` : "Suite files are current",
		);
	}
}
