// Native Pi 0.85.1 conversation-output catalog manifest.
import type {CatalogScene} from './catalog-fixtures';

export type {
  CatalogContent,
  CatalogItem,
  CatalogScene,
  CatalogToolArgs,
  CatalogToolDetails,
  CatalogToolFixture,
  CatalogToolName,
} from './catalog-fixtures';
export {getCatalogScene} from './catalog-fixtures';

export const catalogScenes = [
  {
    name: 'catalog-tool-preview-states',
    title: 'Collapsed read, skill read and generic output',
    expectedToken: 'read',
    expectedTokens: ['more lines', '[skill]'],
    category: 'built-in tools',
    source:
      'Pi 0.85.1 native renderer; static tool data, Web page data via current Content formatter',
  },
  {
    name: 'catalog-tool-empty-errors',
    title: 'Empty retrieval, missing file and edit failure',
    expectedToken: 'retiredCursor',
    expectedTokens: ['ENOENT', 'Could not find'],
    category: 'built-in tools',
    source:
      'Pi 0.85.1 native renderer; static tool data, Web page data via current Content formatter',
  },
  {
    name: 'catalog-tool-bash-truncated',
    title: 'Bash preview, truncation and timeout',
    expectedToken: 'earlier lines',
    expectedTokens: ['Full output:', 'timed out'],
    category: 'built-in tools',
    source:
      'Pi 0.85.1 native renderer; static tool data, Web page data via current Content formatter',
  },
  {
    name: 'catalog-shell-interrupted',
    title: 'Shell cancelled, nonzero exit and truncation',
    expectedToken: 'cancelled',
    expectedTokens: ['exit 1', 'Output truncated'],
    category: 'shell',
    source:
      'Pi 0.85.1 native renderer; static tool data, Web page data via current Content formatter',
  },
  {
    name: 'catalog-web-page',
    title: 'Retained Web content paging',
    expectedToken: 'get_search_content',
    expectedTokens: ['truncated: true', 'nextOffset: 50'],
    category: 'Web',
    source:
      'Pi 0.85.1 native renderer; static tool data, Web page data via current Content formatter',
  },
  {
    name: 'catalog-web-errors',
    title: 'Web batch item error and unavailable content',
    expectedToken: 'HTTP 404',
    expectedTokens: ['Content unavailable'],
    category: 'Web',
    source:
      'Pi 0.85.1 native renderer; static tool data, Web page data via current Content formatter',
  },

  {
    name: 'catalog-user-markdown',
    title: 'User message with Markdown and code',
    expectedToken: 'Review the pagination boundary',
    category: 'conversation',
    source: 'Pi 0.85.1 UserMessageComponent',
  },
  {
    name: 'catalog-assistant-markdown',
    title: 'Assistant Markdown and code',
    expectedToken: 'previousIds',
    category: 'conversation',
    source: 'Pi 0.85.1 AssistantMessageComponent',
  },
  {
    name: 'catalog-assistant-thinking-collapsed',
    title: 'Assistant thinking collapsed',
    expectedToken: 'Thinking...',
    category: 'conversation',
    source: 'Pi 0.85.1 AssistantMessageComponent',
  },
  {
    name: 'catalog-assistant-thinking-expanded',
    title: 'Assistant thinking expanded',
    expectedToken: 'previousIds',
    category: 'conversation',
    source: 'Pi 0.85.1 AssistantMessageComponent',
  },
  {
    name: 'catalog-assistant-error',
    title: 'Assistant provider error',
    expectedToken: 'Error: Provider returned HTTP 503',
    category: 'conversation',
    source: 'Pi 0.85.1 AssistantMessageComponent',
  },
  {
    name: 'catalog-assistant-aborted',
    title: 'Assistant response aborted',
    expectedToken: 'Operation aborted',
    category: 'conversation',
    source: 'Pi 0.85.1 AssistantMessageComponent',
  },
  {
    name: 'catalog-assistant-truncated',
    title: 'Assistant response truncated',
    expectedToken: 'Response was truncated',
    category: 'conversation',
    source: 'Pi 0.85.1 AssistantMessageComponent',
  },
  {
    name: 'catalog-custom-message-fallback',
    title: 'Custom message native fallback',
    expectedToken: 'catalog-fallback',
    category: 'optional extension output',
    source: 'Pi 0.85.1 CustomMessageComponent default renderer',
  },
  {
    name: 'catalog-tool-read',
    title: 'Built-in read tool',
    expectedToken: 'src/search/paginate.ts',
    category: 'built-in tools',
    source: 'Pi 0.85.1 createReadToolDefinition + ToolExecutionComponent',
  },
  {
    name: 'catalog-tool-write',
    title: 'Built-in write tool',
    expectedToken: 'src/search/paginate.test.ts',
    category: 'built-in tools',
    source: 'Pi 0.85.1 createWriteToolDefinition + ToolExecutionComponent',
  },
  {
    name: 'catalog-tool-edit',
    title: 'Built-in edit diff',
    expectedToken: 'src/search/paginate.ts',
    category: 'built-in tools',
    source: 'Pi 0.85.1 createEditToolDefinition + ToolExecutionComponent',
  },
  {
    name: 'catalog-tool-bash-states',
    title: 'Built-in Bash running, complete and failed',
    expectedToken: 'bun test',
    expectedTokens: ['8 pass', 'FAIL skips'],
    category: 'built-in tools',
    source: 'Pi 0.85.1 createBashToolDefinition + ToolExecutionComponent',
  },
  {
    name: 'catalog-tool-grep',
    title: 'Built-in grep tool',
    expectedToken: 'previousIds',
    expectedTokens: ['[Truncated:'],
    category: 'built-in tools',
    source: 'Pi 0.85.1 createGrepToolDefinition + ToolExecutionComponent',
  },
  {
    name: 'catalog-tool-find',
    title: 'Built-in find tool',
    expectedToken: '**/*.ts',
    expectedTokens: ['[Truncated:'],
    category: 'built-in tools',
    source: 'Pi 0.85.1 createFindToolDefinition + ToolExecutionComponent',
  },
  {
    name: 'catalog-tool-ls',
    title: 'Built-in ls tool',
    expectedToken: 'src/search',
    expectedTokens: ['[Truncated:'],
    category: 'built-in tools',
    source: 'Pi 0.85.1 createLsToolDefinition + ToolExecutionComponent',
  },
  {
    name: 'catalog-web-search',
    title: 'Generic Web search output',
    expectedToken: 'web_search',
    expectedTokens: ['contentId:', 'provider: exa', 'snippet:'],
    category: 'Web',
    source:
      'Pi Stuff src/web/tools.ts formatter + Pi 0.85.1 generic ToolExecutionComponent',
  },
  {
    name: 'catalog-web-content',
    title: 'Generic Web fetch content output',
    expectedToken: 'fetch_content',
    expectedTokens: ['contentId:', 'nextOffset:', 'truncated: false'],
    category: 'Web',
    source:
      'Pi Stuff src/web/tools.ts/content.ts formatter + Pi 0.85.1 generic ToolExecutionComponent',
  },
  {
    name: 'catalog-web-page-find',
    title: 'Generic Web retained content find output',
    expectedToken: 'get_search_content',
    expectedTokens: ['contentId:', 'moreMatches:'],
    category: 'Web',
    source:
      'Pi Stuff src/web/content.ts formatter + Pi 0.85.1 generic ToolExecutionComponent',
  },
  {
    name: 'catalog-rtk-rewrite-failure',
    title: 'RTK rewrite Bash and failure notice',
    expectedToken: 'RTK rewrite',
    expectedTokens: [
      'git status',
      'leaving the original Bash command unchanged',
    ],
    category: 'RTK',
    source:
      'Pi Stuff src/rtk/register.ts failureNotice + Pi 0.85.1 Bash renderer/ctx.ui.notify(error)',
  },
  {
    name: 'catalog-rtk-rewrite-success',
    title: 'RTK rewritten Bash command success',
    expectedToken: 'rtk git status',
    category: 'RTK',
    source:
      'Static offline reconstruction of Pi Stuff RTK rewrite + Pi 0.85.1 Bash renderer',
  },
  {
    name: 'catalog-shell-modes',
    title: 'Shell ! and !! output',
    expectedToken: 'git status',
    expectedTokens: ['git diff'],
    category: 'shell',
    source: 'Pi 0.85.1 BashExecutionComponent',
  },
  {
    name: 'catalog-compaction-collapsed',
    title: 'Compaction summary collapsed',
    expectedToken: 'Compacted from',
    category: 'session summaries',
    source: 'Pi 0.85.1 CompactionSummaryMessageComponent',
  },
  {
    name: 'catalog-compaction-expanded',
    title: 'Compaction summary expanded',
    expectedToken: 'previousIds',
    category: 'session summaries',
    source: 'Pi 0.85.1 CompactionSummaryMessageComponent',
  },
  {
    name: 'catalog-branch-collapsed',
    title: 'Branch summary collapsed',
    expectedToken: 'Branch summary',
    category: 'session summaries',
    source: 'Pi 0.85.1 BranchSummaryMessageComponent',
  },
  {
    name: 'catalog-branch-expanded',
    title: 'Branch summary expanded',
    expectedToken: 'previousIds',
    category: 'session summaries',
    source: 'Pi 0.85.1 BranchSummaryMessageComponent',
  },
  {
    name: 'catalog-skill-collapsed',
    title: 'Skill invocation collapsed',
    expectedToken: 'review-pagination',
    category: 'session summaries',
    source: 'Pi 0.85.1 SkillInvocationMessageComponent',
  },
  {
    name: 'catalog-skill-expanded',
    title: 'Skill invocation expanded',
    expectedToken: 'review-pagination',
    category: 'session summaries',
    source: 'Pi 0.85.1 SkillInvocationMessageComponent',
  },
  {
    name: 'catalog-notice-info',
    title: 'Info notice',
    expectedToken: 'using the cached',
    category: 'notices',
    source: 'Pi 0.85.1 ctx.ui.notify(info)',
  },
  {
    name: 'catalog-notice-warning',
    title: 'Warning notice',
    expectedToken: 'Warning: output',
    category: 'notices',
    source: 'Pi 0.85.1 ctx.ui.notify(warning)',
  },
  {
    name: 'catalog-notice-error',
    title: 'Error notice with retry',
    expectedToken: 'Error: the requested operation failed',
    category: 'notices',
    source: 'Pi 0.85.1 ctx.ui.notify(error)',
  },
  {
    name: 'catalog-extension-error',
    title: 'Extension handler error with reload retry hint',
    expectedToken: 'Extension "',
    expectedTokens: ['/reload'],
    category: 'notices',
    source:
      'Pi 0.85.1 ExtensionRunner onError + InteractiveMode.showExtensionError',
  },
  {
    name: 'catalog-tool-image-fallback',
    title: 'Tool image output with text fallback',
    expectedToken: 'image/png',
    expectedTokens: ['[Image:'],
    category: 'media',
    source: 'Pi 0.85.1 ToolExecutionComponent image content',
  },
] as const satisfies readonly CatalogScene[];
